CREATE TABLE [dbo].[p_master_1]
(
[f_cod] [bigint] NOT NULL,
[f_nam] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_fam] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_emt] [int] NULL,
[f_jnc] [int] NULL,
[f_pay] [bigint] NULL,
[f_mos] [bigint] NULL,
[f_fat] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_shn] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_bdt] [datetime] NULL,
[f_osb] [int] NULL,
[f_shb] [int] NULL,
[f_mso] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_bta] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_act] [bit] NULL,
[f_par] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_bom] [bit] NULL,
[f_hat] [int] NULL,
[f_hap] [int] NULL,
[f_gvh] [bit] NULL,
[f_gve] [bit] NULL,
[f_din] [int] NULL,
[f_tmo] [bit] NULL,
[f_mit] [int] NULL,
[f_mat] [int] NULL,
[f_mbt] [int] NULL,
[f_mth] [int] NULL,
[f_mbh] [int] NULL,
[f_mch] [int] NULL,
[f_vsz] [bigint] NULL,
[f_mov] [int] NULL,
[f_yov] [int] NULL,
[f_ebt] [int] NULL,
[f_tpb] [datetime] NULL,
[f_cpm] [bigint] NULL,
[f_ctb] [int] NULL,
[f_ezh] [int] NULL,
[f_ppo] [int] NULL,
[f_brk] [int] NULL,
[f_erf] [int] NULL,
[f_eda] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_nbe] [int] NULL,
[f_sey] [int] NULL,
[f_sem] [int] NULL,
[f_sed] [int] NULL,
[f_mil] [int] NULL,
[f_tah] [int] NULL,
[f_wif] [int] NULL,
[f_vmk] [int] NULL,
[f_tmr] [datetime] NULL,
[f_nap] [int] NULL,
[f_ers] [bit] NULL,
[f_ser] [int] NULL,
[f_tbi] [int] NULL,
[f_shm] [varchar] (20) COLLATE Arabic_CI_AI NULL,
[f_con] [bigint] NULL,
[f_sss] [int] NULL,
[f_sys] [bigint] NULL,
[f_flc] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_isa] [int] NULL,
[f_ola] [int] NULL,
[f_olm] [int] NULL,
[f_vsh] [int] NULL,
[f_hes] [bit] NULL,
[f_mga] [bit] NULL,
[f_bim] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_grp] [int] NULL,
[f_grd] [datetime] NULL,
[f_ngd] [datetime] NULL,
[f_ras] [int] NULL,
[f_shl] [int] NULL,
[f_pos] [int] NULL,
[f_shp] [bit] NULL,
[f_tag] [int] NULL,
[f_rsm] [datetime] NULL,
[f_tes] [datetime] NULL,
[f_osk] [int] NULL,
[f_mna] [int] NULL,
[f_mnm] [int] NULL,
[f_mne] [int] NULL,
[f_mma] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_mmd] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_mta] [int] NULL,
[f_mba] [int] NULL,
[f_mtm] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_mtc] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_vah] [int] NULL,
[f_sba] [int] NULL,
[f_sbm] [int] NULL,
[f_sbr] [int] NULL,
[f_sdc] [int] NULL,
[f_sdm] [int] NULL,
[f_sdr] [int] NULL,
[f_stn] [int] NULL,
[f_stm] [int] NULL,
[f_str] [int] NULL,
[f_sgs] [int] NULL,
[f_sgm] [int] NULL,
[f_sgr] [int] NULL,
[f_kgr] [int] NULL,
[f_kga] [int] NULL,
[f_kgb] [int] NULL,
[f_zsa] [int] NULL,
[f_tpy] [datetime] NULL,
[f_kez] [int] NULL,
[f_kes] [int] NULL,
[f_mjr] [int] NULL,
[f_mjs] [int] NULL,
[f_nkm] [int] NULL,
[f_shk] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_thk] [datetime] NULL,
[f_teh] [datetime] NULL,
[f_smz] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_tmz] [datetime] NULL,
[f_ttk] [datetime] NULL,
[f_ars] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_tlf] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_naz] [int] NULL,
[f_sly] [bigint] NULL,
[f_dms] [int] NULL,
[f_hrz] [float] NULL,
[f_zst] [int] NULL,
[f_tyb] [int] NULL,
[f_gba] [int] NULL,
[f_pba] [int] NULL,
[f_tan] [int] NULL,
[f_jan] [int] NULL,
[f_tva] [int] NULL,
[f_tam] [datetime] NULL,
[f_azm] [datetime] NULL,
[f_psl] [bigint] NULL,
[f_stt] [int] NULL,
[f_fhk] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_fdt] [datetime] NULL,
[f_bsd] [datetime] NULL,
[f_tre] [int] NULL,
[f_tmd] [int] NULL,
[f_tsa] [int] NULL,
[f_tal] [decimal] (18, 3) NULL,
[f_teb] [decimal] (18, 3) NULL,
[f_kbe] [int] NULL,
[f_tbe] [int] NULL,
[f_tem] [int] NULL,
[f_kfr] [int] NULL,
[f_kfb] [int] NULL,
[f_kfm] [int] NULL,
[f_ksd] [int] NULL,
[f_ksg] [int] NULL,
[f_ksm] [int] NULL,
[f_ses] [datetime] NULL,
[f_mbs] [datetime] NULL,
[f_spa] [datetime] NULL,
[f_sbg] [datetime] NULL,
[f_ttt] [datetime] NULL,
[f_ssd] [int] NULL,
[f_msd] [int] NULL,
[f_rsd] [int] NULL,
[f_skh] [int] NULL,
[f_mkh] [int] NULL,
[f_rkh] [int] NULL,
[f_smn] [int] NULL,
[f_mmn] [int] NULL,
[f_rmn] [int] NULL,
[f_pip] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_egr] [int] NULL,
[f_pma] [int] NULL,
[f_psn] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_gev] [int] NULL,
[f_tgr] [int] NULL,
[f_ssb] [int] NULL,
[f_smb] [int] NULL,
[f_srb] [int] NULL,
[f_sdb] [int] NULL,
[f_mdb] [int] NULL,
[f_rdb] [int] NULL,
[f_stb] [int] NULL,
[f_mtb] [int] NULL,
[f_rtb] [int] NULL,
[f_rgm] [int] NULL,
[f_eps] [bigint] NULL,
[f_cpd] [bigint] NULL,
[f_cnb] [int] NULL,
[f_sep] [int] NULL,
[f_tac] [int] NULL,
[f_sch] [int] NULL,
[f_mah] [int] NULL,
[f_tky] [bit] NULL,
[f_heb] [bit] NULL,
[f_hgb] [int] NULL,
[f_fzk] [int] NULL,
[f_pyg] [datetime] NULL,
[f_ram] [bigint] NULL,
[f_tvi] [int] NULL,
[f_unm] [int] NULL,
[f_fic] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_flr] [varchar] (200) COLLATE Arabic_CI_AI NULL,
[f_tcr] [datetime] NULL,
[f_tup] [datetime] NULL,
[description] [ntext] COLLATE Arabic_CI_AI NULL,
[f_razmande] [decimal] (10, 2) NULL,
[f_esarat] [decimal] (10, 2) NULL,
[inx] [int] NULL,
[f_noshql] [int] NULL,
[f_hmtrzsiasi] [int] NULL,
[f_pyehmtrzsiasi] [int] NULL,
[f_rdfhmtrzsiasi] [int] NULL,
[f_nomqamat] [int] NULL,
[f_groohbsji] [int] NULL,
[f_zrbfqbzrsi] [int] NULL,
[f_zrbfqvjh] [int] NULL,
[f_zrbkrbashae] [int] NULL,
[f_sndqbznshtgi] [int] NULL,
[f_snvtbsj] [int] NULL,
[f_nvzbgir] [int] NULL,
[f_pye] [int] NULL,
[f_mrtbh] [int] NULL,
[f_mng_type] [int] NULL,
[f_jangi] [decimal] (10, 2) NULL,
[f_modzmn] [decimal] (10, 2) NULL,
[f_sarzmn] [decimal] (10, 2) NULL,
[PayanKhedmatNo] [varchar] (50) COLLATE Arabic_CI_AI NULL,
[GozineshNo] [varchar] (50) COLLATE Arabic_CI_AI NULL,
[f_class] [int] NULL,
[f_mobile] [varchar] (100) COLLATE Arabic_CI_AI NULL,
[f_email] [varchar] (100) COLLATE Arabic_CI_AI NULL,
[IsChanged] [tinyint] NULL,
[HesabNo] [varchar] (50) COLLATE Arabic_CI_AI NULL,
[BabkName] [varchar] (100) COLLATE Arabic_CI_AI NULL,
[ShobeName] [varchar] (100) COLLATE Arabic_CI_AI NULL,
[ShobeNo] [varchar] (50) COLLATE Arabic_CI_AI NULL,
[MaghamDate] [datetime] NULL,
[MaghamId] [int] NULL,
[f_nbe_Dsd] [int] NULL,
[tamayol_bime_baz] [bit] NULL,
[next_class_date] [datetime] NULL,
[next_ctb_date] [datetime] NULL,
[f_cod_new] [bigint] NULL,
[f_cod_old] [bigint] NULL,
[karaneh] [int] NULL,
[karanehVijhe] [int] NULL,
[DarsadMabna] [int] NULL,
[f_t_isa] [int] NULL,
[f_t_ash] [int] NULL,
[f_t_pay] [int] NULL,
[Goroh_arzyabi] [int] NULL,
[f_emp_rule] [int] NULL,
[f_shn_seri] [int] NULL,
[date_of_30_years] [datetime] NULL,
[f_meli_seri] [nvarchar] (10) COLLATE Arabic_CI_AI NULL,
[baz_number] [nvarchar] (50) COLLATE Arabic_CI_AI NULL,
[test_1] [nvarchar] (10) COLLATE Persian_100_CI_AI NULL,
[test_11] [nvarchar] (10) COLLATE Persian_100_CI_AI NULL,
[test_121] [nvarchar] (10) COLLATE Persian_100_CI_AI NULL,
[test_1234] [nvarchar] (10) COLLATE Persian_100_CI_AI NULL,
[test_123] [nvarchar] (10) COLLATE Persian_100_CI_AI NULL,
[test_12345] [nvarchar] (10) COLLATE Persian_100_CI_AI NULL,
[test_123456] [nchar] (10) COLLATE Persian_100_CI_AI NULL,
[test_1212] [varchar] (50) COLLATE Persian_100_CI_AI NULL,
[tttrt] [nchar] (10) COLLATE Persian_100_CI_AI NULL
) ON [PRIMARY]
GO
